AWSTemplateFormatVersion: '2010-09-09'

Resources:

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for S3 encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect : Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  rawS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "RawBucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKey

Outputs:
  BucketName:
    Value: !Ref rawS3Bucket

  KMSKeyArn:
    Value: !GetAtt KMSKey.Arn