AWSTemplateFormatVersion: '2010-09-09'

Resources:

  RawReaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: RawReaderQueue
      VisibilityTimeout: 60
      MessageRetentionPeriod: 345600  # 4 days
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt RawReaderQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: arn:aws:s3:::raw-bucket-287972983990

Outputs:

  QueueUrl:
    Value: !Ref RawReaderQueue

  QueueArn:
    Value: !GetAtt RawReaderQueue.Arn
    Export:
      Name: RawReaderQueue-Arn