AWSTemplateFormatVersion: '2010-09-09'
Description: Create DynamoDB Table2

Resources:
  SourceCache:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SourceCache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      KeySchema:
        - AttributeName: Id
          KeyType: HASH

Outputs:
  SourceCacheStreamArn:
    Value: !GetAtt SourceCache.StreamArn
    Export:
      Name: SourceCache-StreamArn