AWSTemplateFormatVersion: '2010-09-09'
Description: Create DynamoDB Table

Resources:
  PartyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SourceCache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Data
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH